/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticateRouteImport } from './routes/authenticate'
import { Route as DashboardLayoutRouteImport } from './routes/dashboard/layout'
import { Route as PublicLayoutRouteImport } from './routes/_public/layout'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as DashboardFileTestRouteImport } from './routes/dashboard/file-test'
import { Route as PublicLaunchesRouteImport } from './routes/_public/launches'
import { Route as PublicProductsIndexRouteImport } from './routes/_public/products/index'
import { Route as DashboardProductsNewRouteImport } from './routes/dashboard/products/new'
import { Route as DashboardTestTestATestBTestCTestRouteImport } from './routes/dashboard/test/test-a/test-b/test-c/test'

const AuthenticateRoute = AuthenticateRouteImport.update({
  id: '/authenticate',
  path: '/authenticate',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLayoutRoute = DashboardLayoutRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicLayoutRoute = PublicLayoutRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const DashboardFileTestRoute = DashboardFileTestRouteImport.update({
  id: '/file-test',
  path: '/file-test',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const PublicLaunchesRoute = PublicLaunchesRouteImport.update({
  id: '/launches',
  path: '/launches',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const PublicProductsIndexRoute = PublicProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const DashboardProductsNewRoute = DashboardProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardTestTestATestBTestCTestRoute =
  DashboardTestTestATestBTestCTestRouteImport.update({
    id: '/test/test-a/test-b/test-c/test',
    path: '/test/test-a/test-b/test-c/test',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/dashboard': typeof DashboardLayoutRouteWithChildren
  '/authenticate': typeof AuthenticateRoute
  '/launches': typeof PublicLaunchesRoute
  '/dashboard/file-test': typeof DashboardFileTestRoute
  '/': typeof PublicIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/products/new': typeof DashboardProductsNewRoute
  '/products': typeof PublicProductsIndexRoute
  '/dashboard/test/test-a/test-b/test-c/test': typeof DashboardTestTestATestBTestCTestRoute
}
export interface FileRoutesByTo {
  '/authenticate': typeof AuthenticateRoute
  '/launches': typeof PublicLaunchesRoute
  '/dashboard/file-test': typeof DashboardFileTestRoute
  '/': typeof PublicIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/products/new': typeof DashboardProductsNewRoute
  '/products': typeof PublicProductsIndexRoute
  '/dashboard/test/test-a/test-b/test-c/test': typeof DashboardTestTestATestBTestCTestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicLayoutRouteWithChildren
  '/dashboard': typeof DashboardLayoutRouteWithChildren
  '/authenticate': typeof AuthenticateRoute
  '/_public/launches': typeof PublicLaunchesRoute
  '/dashboard/file-test': typeof DashboardFileTestRoute
  '/_public/': typeof PublicIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/products/new': typeof DashboardProductsNewRoute
  '/_public/products/': typeof PublicProductsIndexRoute
  '/dashboard/test/test-a/test-b/test-c/test': typeof DashboardTestTestATestBTestCTestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard'
    | '/authenticate'
    | '/launches'
    | '/dashboard/file-test'
    | '/'
    | '/dashboard/'
    | '/dashboard/products/new'
    | '/products'
    | '/dashboard/test/test-a/test-b/test-c/test'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/authenticate'
    | '/launches'
    | '/dashboard/file-test'
    | '/'
    | '/dashboard'
    | '/dashboard/products/new'
    | '/products'
    | '/dashboard/test/test-a/test-b/test-c/test'
  id:
    | '__root__'
    | '/_public'
    | '/dashboard'
    | '/authenticate'
    | '/_public/launches'
    | '/dashboard/file-test'
    | '/_public/'
    | '/dashboard/'
    | '/dashboard/products/new'
    | '/_public/products/'
    | '/dashboard/test/test-a/test-b/test-c/test'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicLayoutRoute: typeof PublicLayoutRouteWithChildren
  DashboardLayoutRoute: typeof DashboardLayoutRouteWithChildren
  AuthenticateRoute: typeof AuthenticateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/authenticate': {
      id: '/authenticate'
      path: '/authenticate'
      fullPath: '/authenticate'
      preLoaderRoute: typeof AuthenticateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/dashboard/file-test': {
      id: '/dashboard/file-test'
      path: '/file-test'
      fullPath: '/dashboard/file-test'
      preLoaderRoute: typeof DashboardFileTestRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_public/launches': {
      id: '/_public/launches'
      path: '/launches'
      fullPath: '/launches'
      preLoaderRoute: typeof PublicLaunchesRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_public/products/': {
      id: '/_public/products/'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof PublicProductsIndexRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/dashboard/products/new': {
      id: '/dashboard/products/new'
      path: '/products/new'
      fullPath: '/dashboard/products/new'
      preLoaderRoute: typeof DashboardProductsNewRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/test/test-a/test-b/test-c/test': {
      id: '/dashboard/test/test-a/test-b/test-c/test'
      path: '/test/test-a/test-b/test-c/test'
      fullPath: '/dashboard/test/test-a/test-b/test-c/test'
      preLoaderRoute: typeof DashboardTestTestATestBTestCTestRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
  }
}

interface PublicLayoutRouteChildren {
  PublicLaunchesRoute: typeof PublicLaunchesRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicProductsIndexRoute: typeof PublicProductsIndexRoute
}

const PublicLayoutRouteChildren: PublicLayoutRouteChildren = {
  PublicLaunchesRoute: PublicLaunchesRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicProductsIndexRoute: PublicProductsIndexRoute,
}

const PublicLayoutRouteWithChildren = PublicLayoutRoute._addFileChildren(
  PublicLayoutRouteChildren,
)

interface DashboardLayoutRouteChildren {
  DashboardFileTestRoute: typeof DashboardFileTestRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardProductsNewRoute: typeof DashboardProductsNewRoute
  DashboardTestTestATestBTestCTestRoute: typeof DashboardTestTestATestBTestCTestRoute
}

const DashboardLayoutRouteChildren: DashboardLayoutRouteChildren = {
  DashboardFileTestRoute: DashboardFileTestRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardProductsNewRoute: DashboardProductsNewRoute,
  DashboardTestTestATestBTestCTestRoute: DashboardTestTestATestBTestCTestRoute,
}

const DashboardLayoutRouteWithChildren = DashboardLayoutRoute._addFileChildren(
  DashboardLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PublicLayoutRoute: PublicLayoutRouteWithChildren,
  DashboardLayoutRoute: DashboardLayoutRouteWithChildren,
  AuthenticateRoute: AuthenticateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
