export const categories: string[] = [
  "no-code",
  "automation",
  "integrations",
  "saas",
  "messaging",
  "pubsub",
  "realtime",
  "observability",
  "edge",
  "cache",
  "performance",
  "database",
  "cloud",
  "distributed",
  "serverless",
  "design-system",
  "ui",
  "react",
  "accessibility",
  "security",
  "auth",
  "sso",
  "identity",
  "fintech",
  "analytics",
  "streaming",
  "tracing",
  "metrics",
  "agent",
  "layout",
  "css",
  "media",
  "sync",
  "offline",
  "sdk",
  "orchestration",
  "microservices",
  "workflow",
  "forms",
  "documents",
  "api",
  "pdf",
  "ledger",
  "compliance",
  "feature-flags",
  "devops",
  "sql",
  "data-engineering",
  "theming",
  "tokens",
  // additional common tech/software categories
  "monitoring",
  "logging",
  "ci-cd",
  "deployment",
  "testing",
  "search",
  "storage",
  "backup",
  "machine-learning",
  "ai",
  "mobile",
  "iot",
  "blockchain",
  "payments",
  "collaboration",
];

/**
 * Common reasons for reporting comments, reviews, etc.
 */
export const reportReasons: string[] = [
  "Spam",
  "Harassment or bullying",
  "Hate speech",
  "Inappropriate content",
  "False information",
  "Copyright violation",
  "Privacy violation",
  "Other",
];
